module.exports = {
    salutationId: 'Salutation',
    departmentId: 'Department',
    leadSourceId: 'LeadSource',
    leadStatusId: 'DispositionStatus',
    contactStatusId: 'DispositionStatus',
    dispositionStatusId: 'DispositionStatus',
    campaignId: 'Campaigns',
    leadOwnerId: 'User',
    contactOwnerId: 'User',
    industryId: 'Industry',
    vendorId: 'Vendor',
    manufacturerId: 'Manufacturer',
    productCategoryId: 'ProductCategory',
    unitId: 'Units',
    productOwnerId: 'User',
    handlerId: 'User',
    buyingRoleId: 'BuyingRole',
    accountId: 'Account',
    meetingOwnerId: 'User',
    leadId: 'Lead',
    contactId: 'Contact',
    callOwnerId: 'User',
    assignToId: 'User',
    todoOwnerId: 'User',
    outcomeId: 'Outcome',
    emailTemplateCategoryId: 'EmailTemplateCategory',
};
